export const TEMPLATE = 'template';

//Auth

//User
export const AUTH_USER = 'AUTH_USER'
export const UNAUTH_USER = 'UNAUTH_USER'
export const FETCHING_USER = 'FETCHING_USER'
export const FETCHING_USER_FAILURE = 'FETCHING_USER_FAILURE'
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS'
export const REMOVE_FETCHING_USER = 'REMOVE_FETCHING_USER'

//Feed
export const FETCHING_FEED_DATA = 'FETCHING_FEED_DATA'
export const FETCHING_POSTS_ERROR = 'FETCHING_POSTS_ERROR'
export const FETCHING_POSTS_SUCCESS = 'FETCHING_POSTS_SUCCESS'
export const FETCHING_USER_POSTS_SUCCESS = 'FETCHING_USER_POSTS_SUCCESS'
export const FETCHING_REPLIES_SUCCESS = 'FETCHING_REPLIES_SUCCESS'
export const POSTING_REPLY_SUCCESS = 'POSTING_REPLY_SUCCESS'
export const POSTING_REPLY_ERROR = 'POSTING_REPLY_ERROR'
export const POSTING_FEED_DATA = 'POSTING_FEED_DATA'
export const ADD_POST = 'ADD_POST'
export const REMOVE_LIKE = 'REMOVE_LIKE'
export const ADD_LIKE = 'ADD_LIKE'
export const ADD_REPLY = 'ADD_REPLY'
export const UPDATE_REPLY_TEXT = 'UPDATE_REPLY_TEXT'
export const ADD_MULTIPLE_POSTS = 'ADD_MULTIPLE_POSTS'

//NewPosts
export const FETCHING_ENTITIES = 'FETCHING_ENTITIES'
export const FETCHING_ENTITIES_SUCCESS = 'FETCHING_ENTITIES_SUCCESS'
export const FETCHING_ENTITIES_ERROR = 'FETCHING_ENTITIES_ERROR'
export const POSTING_NEWPOST = 'POSTING_NEWPOST'
export const POSTING_NEWPOST_SUCCESS = 'POSTING_NEWPOST_SUCCESS'
export const POSTING_NEWPOST_ERROR = 'POSTING_NEWPOST_ERROR'
export const ADD_TO_CIRCLE = 'ADD_TO_CIRCLE'
export const REMOVE_FROM_CIRCLE = 'REMOVE_FROM_CIRCLE'
export const CLEAR_CIRCLE = 'CLEAR_CIRCLE'
export const UPDATE_NEWPOST_TEXT = 'UPDATE_NEWPOST_TEXT'

//Commons
export const REMOVE_FETCHING = 'REMOVE_FETCHING'
export const REMOVE_POSTING = 'REMOVE_POSTING'