export const TEMPLATE = 'template';

//Auth

//User
export const AUTH_USER = 'AUTH_USER'
export const UNAUTH_USER = 'UNAUTH_USER'
export const FETCHING_USER = 'FETCHING_USER'
export const FETCHING_USER_FAILURE = 'FETCHING_USER_FAILURE'
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS'
export const REMOVE_FETCHING_USER = 'REMOVE_FETCHING_USER'

//Posts
export const FETCHING_POSTS = 'FETCHING_POSTS'
export const FETCHING_POSTS_ERROR = 'FETCHING_POSTS_ERROR'
export const FETCHING_POSTS_SUCCESS = 'FETCHING_POSTS_SUCCESS'
export const ADD_POST = 'ADD_POST'
export const ADD_MULTIPLE_POSTS = 'ADD_MULTIPLE_POSTS'
export const REMOVE_FETCHING = 'REMOVE_FETCHING'